# Announcer v1.0Beta
# by BeYkeRYkt
Announce:
  BeYkeRYkt: true
  Dinnerspond_: true
  BIGSteve: true
  Dinnerbone: true
Lang:
  Disable: 'Announcer disabled for: '
  Enable: 'Announcer enabled for: '
