# HockeyGame v2.1 Configuration
# Have fun :3
# by BeYkeRYkt
Enable-updater: true
Lang: English
Game:
  MatchTimer: 200
  MusicMatch: true
  puck:
    material: RECORD_7
  PowerBeat:
    Winger: 0.6
    Defender: 0.4
    Goalkeeper: 0.3
  Rewards:
    Winners:
    - '266:3'
    - '264:1'
    Losers:
    - '1:1'
Whitelist-commands:
- hockey
- msg
- reload
- kick
- ban
