name: HockeyGame
main: ykt.BeYkeRYkt.HockeyGame.HG
description: Plugin for players :D
author: BeYkeRYkt
version: 2.2
commands:
  hockey:
    description: Main commands
    usage: /<command> [args]
permissions:
  hg.admin:
    default: false
  hg.playing:
    default: true